spring:
  application:
    name: product
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      password: ${CONFIG_PASSWORD:nimadirxavfsizlik}
      username: user
  config:
    import: 'configserver:'
  profiles:
    active: local