spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: local
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      password: ${CONFIG_PASSWORD:nimadirxavfsizlik}
      username: user

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty: DEBUG